
linters:
  enable:
  - whitespace
  - gosec
  - gci
  - gofmt
  - goimports
  - revive
  - nilerr
  - nestif
  - goconst
  - asasalint
linter-settings:
  gosec:
    excludes:
      - G107
config:
  global:
    nosec: false