
linters:
  enable:
  - whitespace
  - gosec
  - gci
  - gofmt
  - goimports
  - revive
  - nilerr
  - nestif
  - goconst
  - asasalint
  - bodyclose
  - dupl
  - durationcheck
  - errname
  - goconst
  - godox
  - gofumpt
  - importas
  - unconvert
  - unparam
linter-settings:
  nestif:
    min-complexity: 20
  gosec:
    excludes:
      - G107
config:
  global:
    nosec: false