name: Build and release artifacts
on:
  release:
    types: 
      - created

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: "linux/amd64, darwin/amd64, windows/amd64"
          package: ""
          name: "mmt"
          compress: "false"
          dest: "dist"
      - name: Upload assets for Windows
        uses: actions/upload-artifact@v2
        with:
          name: mmt-win
          path: dist-win/*
      - name: Upload assets for Linux
        uses: actions/upload-artifact@v2
        with:
          name: mmt-linux
          path: dist-linux/*
      - name: Upload assets for Mac OS
        uses: actions/upload-artifact@v2
        with:
          name: mmt-darwin
          path: dist-darwin/*
