name: Test
on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - uses: FedericoCarboni/setup-ffmpeg@v2
      id: setup-ffmpeg
    - name: Test
      run: go test -v -race ./...